import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import { MetadataDatabase } from '../src/server/storage/database';
import { evidenceKey } from '../src/server/validation/key';
import { RuntimeManager } from '../src/server/runtime/manager';
import { loadRegistry } from '../src/server/transport/registry';
import { HerdrTarget } from '../src/server/transport/herdr-target';
import { createHost } from '../src/server/host';
import { validateLocalControl } from '../src/server/validation/automatic';

const host = process.env.HOST ?? '127.0.0.1';
const port = Number(process.env.PORT ?? 4321);
const origin = process.env.HERDR_WEB_ORIGIN ?? `http://${host}:${port}`;
if (new URL(origin).origin !== origin || new URL(origin).username || new URL(origin).password) throw new Error('HERDR_WEB_ORIGIN must be a normalized HTTP or HTTPS origin without credentials or a path');
if (!['http:', 'https:'].includes(new URL(origin).protocol)) throw new Error('HERDR_WEB_ORIGIN must use HTTP or HTTPS');
const local = ['127.0.0.1', 'localhost', '::1'].includes(host);
if (!local && (!origin.startsWith('https://') || process.env.HERDR_WEB_TRUSTED_HTTPS !== '1')) throw new Error('Nonlocal binding requires explicitly trusted HTTPS');
if (!Number.isInteger(port) || port < 1 || port > 65535) throw new Error('Invalid port');
const database = new MetadataDatabase(process.env.HERDR_WEB_DATABASE ?? '.data/gateway.sqlite');
const key = evidenceKey(database);
const profiles = await loadRegistry(process.env.HERDR_WEB_TARGETS);
const manager = new RuntimeManager(database, profiles.map((profile) => new HerdrTarget(profile, { read: () => database.getSetting('validation:' + profile.id), key })));
const { handler } = await import(pathToFileURL(resolve('dist/server/entry.mjs')).href);
const tls = process.env.HERDR_WEB_TLS_CERT && process.env.HERDR_WEB_TLS_KEY ? { cert: await readFile(process.env.HERDR_WEB_TLS_CERT), key: await readFile(process.env.HERDR_WEB_TLS_KEY) } : undefined;
const app = await createHost(manager, origin, handler, tls);
await app.listen({ host, port });
const automaticLocal = profiles.find((profile) => profile.id === 'local' && profile.automatic && profile.transport === 'local');
let validationStarted = false;
manager.on('projection', (projection) => {
  if (!automaticLocal || validationStarted || !projection.connected || projection.machineId !== automaticLocal.id) return;
  validationStarted = true;
  const fingerprint = manager.supervisors.get(automaticLocal.id)!.target.fingerprint;
  void validateLocalControl(automaticLocal, database, key, fingerprint).then((approved) => {
    if (approved) manager.supervisors.get(automaticLocal.id)?.invalidate();
    else console.warn('Automatic control validation did not approve terminal input');
  }).catch((error) => console.warn('Automatic control validation stopped:', error instanceof Error ? error.message : 'unknown error'));
});
manager.start();
console.log(`Herdr Web listening at ${origin}; unproved capabilities are disabled`);
for (const signal of ['SIGINT', 'SIGTERM'] as const) process.once(signal, () => { void app.close().finally(() => { database.close(); process.exit(0); }); });
