import { z } from 'zod';

const id = z.string().min(1).max(160);
const rect = z.object({ x: z.number().int().nonnegative(), y: z.number().int().nonnegative(), width: z.number().int().nonnegative(), height: z.number().int().nonnegative() });
export const nativePane = z.object({ pane_id: id, terminal_id: id, workspace_id: id, tab_id: id, focused: z.boolean(), revision: z.number().int().nonnegative(), agent_status: z.enum(['idle', 'working', 'blocked', 'done', 'unknown']), agent: z.string().nullable().optional(), title: z.string().nullable().optional(), cwd: z.string().nullable().optional(), terminal_title_stripped: z.string().nullable().optional() });
export const nativeTab = z.object({ tab_id: id, workspace_id: id, label: z.string().nullable().optional() });
export const nativeWorkspace = z.object({ workspace_id: id, label: z.string(), worktree: z.object({ repo_key: id, repo_name: z.string(), repo_root: z.string(), checkout_path: z.string(), is_linked_worktree: z.boolean() }).nullable().optional() });
export const nativeSnapshot = z.object({ version: z.string(), protocol: z.literal(22), workspaces: z.array(nativeWorkspace).max(1000), tabs: z.array(nativeTab).max(2000), panes: z.array(nativePane).max(4000), layouts: z.array(z.object({ workspace_id: id, tab_id: id, area: rect, panes: z.array(z.object({ pane_id: id, rect })).max(256) })).max(2000), agents: z.array(z.object({ terminal_id: id, state_change_seq: z.number().int().nonnegative().optional() })).max(4000) });
export type NativeSnapshot = z.infer<typeof nativeSnapshot>;
export const lifecycleSubscriptions = ['workspace.created', 'workspace.updated', 'workspace.metadata_updated', 'workspace.closed', 'workspace.renamed', 'workspace.moved', 'workspace.reordered', 'worktree.created', 'worktree.opened', 'worktree.removed', 'tab.created', 'tab.closed', 'tab.renamed', 'tab.moved', 'pane.created', 'pane.closed', 'pane.updated', 'pane.moved', 'pane.exited', 'pane.agent_detected', 'layout.updated'].map((type) => ({ type }));
